const now = new Date()
const hoursAgo = (h) => new Date(now - h * 3600000).toISOString()
const daysAgo = (d) => new Date(now - d * 86400000).toISOString()

export const CONSULTORAS = [
  { id: 'c1', nome: 'Tatiane', ativo: true },
  { id: 'c2', nome: 'Júlia', ativo: true },
  { id: 'c3', nome: 'Ketlen', ativo: true },
  { id: 'c4', nome: 'Roger', ativo: false },
  { id: 'c5', nome: 'Tainá', ativo: false },
]

export const CONVERSAS = [
  {
    id: 'cv1',
    contato_nome: 'Maria Aparecida',
    contato_numero: '11999001001',
    consultora: 'Tatiane',
    status: 'quente',
    score_ia: 87,
    classificacao_ia: 'quente',
    chance_fechamento: 82,
    ultima_mensagem_at: hoursAgo(1.2),
    ultima_mensagem_texto: 'Quanto custa o curso mesmo? Posso parcelar?',
    total_mensagens: 14,
    resumo_ia: 'Lead demonstrou interesse real no curso EJA. Perguntou sobre preço e parcelamento. Alta intenção de compra. Já recebeu link do checkout.',
    objecoes_detectadas: ['Preço elevado para o orçamento', 'Quer parcelar em mais vezes'],
    erros_consultora: ['Demorou 3h para responder', 'Não enviou o link na primeira oportunidade'],
    sugestoes_ia: ['Oferecer parcelamento em 12x', 'Reforçar benefício do certificado reconhecido', 'Criar urgência com vagas limitadas'],
    proxima_melhor_resposta: 'Oi Maria! O curso pode ser parcelado em até 12x sem juros no cartão. Hoje ainda temos 3 vagas na turma da manhã. Posso confirmar sua inscrição? 😊',
    recebeu_valor: true,
    recebeu_link: true,
    follow_up_enviado: false,
    tempo_resposta_medio: 45,
    tags: ['recebeu_valor', 'recebeu_link'],
  },
  {
    id: 'cv2',
    contato_nome: 'José Carlos Silva',
    contato_numero: '11988002002',
    consultora: 'Júlia',
    status: 'morno',
    score_ia: 61,
    classificacao_ia: 'morno',
    chance_fechamento: 45,
    ultima_mensagem_at: hoursAgo(5),
    ultima_mensagem_texto: 'Vou pensar e te falo',
    total_mensagens: 8,
    resumo_ia: 'Lead mostrou interesse inicial mas está hesitante. Perguntou sobre modalidade EAD. Consultora enviou valor mas não houve resposta sobre link.',
    objecoes_detectadas: ['Prefere presencial', 'Não tem certeza sobre tempo disponível'],
    erros_consultora: ['Não perguntou sobre objeções', 'Enviou mensagem muito longa e técnica'],
    sugestoes_ia: ['Perguntar qual horário é melhor para ele', 'Destacar flexibilidade do EAD', 'Fazer follow-up amanhã cedo'],
    proxima_melhor_resposta: 'Oi José! Entendo que precisa pensar. Só queria saber: qual seria o maior desafio pra você começar agora? Assim posso te ajudar melhor 🙂',
    recebeu_valor: true,
    recebeu_link: false,
    follow_up_enviado: false,
    tempo_resposta_medio: 120,
    tags: ['recebeu_valor'],
  },
  {
    id: 'cv3',
    contato_nome: 'Ana Paula Ferreira',
    contato_numero: '21977003003',
    consultora: 'Ketlen',
    status: 'vendido',
    score_ia: 95,
    classificacao_ia: 'vendido',
    chance_fechamento: 100,
    ultima_mensagem_at: hoursAgo(3),
    ultima_mensagem_texto: 'Perfeito! Fiz o pagamento agora 🎉',
    total_mensagens: 22,
    resumo_ia: 'Lead convertida com sucesso. Pagamento confirmado. Excelente abordagem da consultora com foco nos benefícios do certificado.',
    objecoes_detectadas: [],
    erros_consultora: [],
    sugestoes_ia: ['Solicitar indicação de amigos', 'Enviar grupo de alunos para engajamento'],
    proxima_melhor_resposta: 'Parabéns Ana! Seja bem-vinda! Vou te adicionar no grupo da turma agora 🎓',
    recebeu_valor: true,
    recebeu_link: true,
    follow_up_enviado: true,
    tempo_resposta_medio: 18,
    tags: ['recebeu_valor', 'recebeu_link'],
  },
  {
    id: 'cv4',
    contato_nome: 'Roberto Mendes',
    contato_numero: '31966004004',
    consultora: 'Tatiane',
    status: 'frio',
    score_ia: 22,
    classificacao_ia: 'frio',
    chance_fechamento: 12,
    ultima_mensagem_at: hoursAgo(26),
    ultima_mensagem_texto: 'Não tenho interesse no momento',
    total_mensagens: 4,
    resumo_ia: 'Lead demonstrou desinteresse desde o início. Respondeu de forma breve e negativa. Baixa probabilidade de conversão no curto prazo.',
    objecoes_detectadas: ['Sem tempo no momento', 'Não vê necessidade do certificado agora'],
    erros_consultora: ['Abordagem muito agressiva na primeira mensagem', 'Não identificou necessidade real'],
    sugestoes_ia: ['Colocar em lista de nurturing para 30 dias', 'Não insistir neste momento'],
    proxima_melhor_resposta: 'Tudo bem Roberto! Quando for o momento certo, pode me chamar. Estarei aqui 😊',
    recebeu_valor: false,
    recebeu_link: false,
    follow_up_enviado: false,
    tempo_resposta_medio: 360,
    tags: [],
  },
  {
    id: 'cv5',
    contato_nome: 'Luciana Costa',
    contato_numero: '11955005005',
    consultora: 'Júlia',
    status: 'quente',
    score_ia: 79,
    classificacao_ia: 'quente',
    chance_fechamento: 71,
    ultima_mensagem_at: hoursAgo(0.5),
    ultima_mensagem_texto: 'Tem turma presencial em São Paulo?',
    total_mensagens: 11,
    resumo_ia: 'Lead muito engajada, fazendo perguntas detalhadas sobre o curso. Interesse genuíno na modalidade presencial em SP.',
    objecoes_detectadas: ['Prefere presencial ao EAD'],
    erros_consultora: ['Não confirmou disponibilidade de turma presencial antes de continuar'],
    sugestoes_ia: ['Verificar turmas presenciais disponíveis em SP', 'Oferecer híbrido como alternativa', 'Manter ritmo de resposta rápido'],
    proxima_melhor_resposta: 'Oi Luciana! Sim, temos turma presencial em SP com início semana que vem! São as terças e quintas, das 19h às 21h. Tenho uma vaga disponível pra você 🗓️',
    recebeu_valor: true,
    recebeu_link: false,
    follow_up_enviado: false,
    tempo_resposta_medio: 12,
    tags: ['recebeu_valor'],
  },
  {
    id: 'cv6',
    contato_nome: 'Fernando Lima',
    contato_numero: '85944006006',
    consultora: 'Ketlen',
    status: 'morno',
    score_ia: 54,
    classificacao_ia: 'morno',
    chance_fechamento: 38,
    ultima_mensagem_at: hoursAgo(8),
    ultima_mensagem_texto: 'Vou ver com minha esposa e te respondo',
    total_mensagens: 9,
    resumo_ia: 'Lead interessa do mas depende de aprovação familiar para fechar. Situação comum — precisa de argumento para o cônjuge.',
    objecoes_detectadas: ['Precisa de aprovação da esposa', 'Questão financeira em família'],
    erros_consultora: ['Não explorou argumento de retorno financeiro do certificado', 'Poderia ter pedido para incluir a esposa na conversa'],
    sugestoes_ia: ['Enviar material sobre retorno salarial com o certificado', 'Sugerir que a esposa também pode fazer o curso', 'Follow-up após 24h'],
    proxima_melhor_resposta: 'Oi Fernando! Boa ideia conversar com sua esposa. Sabia que muitos casais fazem o curso juntos e ainda têm 20% de desconto? Posso explicar pra vocês dois? 😊',
    recebeu_valor: true,
    recebeu_link: false,
    follow_up_enviado: false,
    tempo_resposta_medio: 95,
    tags: ['recebeu_valor'],
  },
  {
    id: 'cv7',
    contato_nome: 'Patrícia Oliveira',
    contato_numero: '41933007007',
    consultora: 'Tatiane',
    status: 'quente',
    score_ia: 83,
    classificacao_ia: 'quente',
    chance_fechamento: 77,
    ultima_mensagem_at: hoursAgo(2),
    ultima_mensagem_texto: 'Que ótimo! Me manda o link pra eu fazer a inscrição',
    total_mensagens: 17,
    resumo_ia: 'Lead pediu o link de inscrição espontaneamente. Consultora deve enviar imediatamente para não perder momentum.',
    objecoes_detectadas: [],
    erros_consultora: ['Ainda não enviou o link (2h depois do pedido)'],
    sugestoes_ia: ['URGENTE: Enviar link agora!', 'Acompanhar se clicou em até 30min'],
    proxima_melhor_resposta: 'Patrícia, aqui está o link: [link]. Qualquer dúvida no processo, me chama! 🚀',
    recebeu_valor: true,
    recebeu_link: false,
    follow_up_enviado: false,
    tempo_resposta_medio: 30,
    tags: ['recebeu_valor'],
  },
  {
    id: 'cv8',
    contato_nome: 'Carlos Eduardo',
    contato_numero: '62922008008',
    consultora: 'Júlia',
    status: 'perdido',
    score_ia: 8,
    classificacao_ia: 'perdido',
    chance_fechamento: 3,
    ultima_mensagem_at: daysAgo(3),
    ultima_mensagem_texto: 'Achei outro curso mais barato, valeu',
    total_mensagens: 6,
    resumo_ia: 'Lead perdido para concorrência por preço. Saiu após comparar valores. Oportunidade de revisar estratégia de preço.',
    objecoes_detectadas: ['Preço acima da concorrência'],
    erros_consultora: ['Não diferenciou o produto da concorrência', 'Não usou depoimentos de alunos'],
    sugestoes_ia: ['Registrar como perdido para concorrência', 'Analisar diferenciadores para futuros leads'],
    proxima_melhor_resposta: null,
    recebeu_valor: true,
    recebeu_link: false,
    follow_up_enviado: false,
    tempo_resposta_medio: 180,
    tags: ['recebeu_valor'],
  },
  {
    id: 'cv9',
    contato_nome: 'Simone Rodrigues',
    contato_numero: '51911009009',
    consultora: 'Ketlen',
    status: 'quente',
    score_ia: 91,
    classificacao_ia: 'quente',
    chance_fechamento: 88,
    ultima_mensagem_at: hoursAgo(0.3),
    ultima_mensagem_texto: 'Posso pagar no débito?',
    total_mensagens: 19,
    resumo_ia: 'Lead no final do funil, perguntando sobre forma de pagamento. Muito próxima do fechamento.',
    objecoes_detectadas: ['Prefere débito ao crédito'],
    erros_consultora: [],
    sugestoes_ia: ['Confirmar aceitação de débito', 'Ter alternativa de Pix caso débito não seja aceito'],
    proxima_melhor_resposta: 'Simone, aceitamos débito sim! Também temos Pix com 5% de desconto à vista. Qual prefere? 😊',
    recebeu_valor: true,
    recebeu_link: true,
    follow_up_enviado: false,
    tempo_resposta_medio: 8,
    tags: ['recebeu_valor', 'recebeu_link'],
  },
  {
    id: 'cv10',
    contato_nome: 'Marcos Vinicius',
    contato_numero: '21900010010',
    consultora: 'Tatiane',
    status: 'morno',
    score_ia: 48,
    classificacao_ia: 'morno',
    chance_fechamento: 33,
    ultima_mensagem_at: hoursAgo(12),
    ultima_mensagem_texto: 'Tá bom, quando tiver mais informação eu entro em contato',
    total_mensagens: 7,
    resumo_ia: 'Lead passivo, aguardando informações adicionais. Consultora pode retomar com material de prova social.',
    objecoes_detectadas: ['Quer mais informações antes de decidir', 'Não sente urgência'],
    erros_consultora: ['Não criou urgência', 'Não enviou depoimentos ou provas sociais'],
    sugestoes_ia: ['Enviar depoimentos de alunos formados', 'Criar senso de urgência com vagas limitadas', 'Follow-up em 24h'],
    proxima_melhor_resposta: 'Oi Marcos! Separei aqui um depoimento de um aluno que estava na mesma situação que você e hoje já tem o certificado 📜. Posso te enviar?',
    recebeu_valor: true,
    recebeu_link: false,
    follow_up_enviado: false,
    tempo_resposta_medio: 75,
    tags: ['recebeu_valor'],
  },
  {
    id: 'cv11',
    contato_nome: 'Daniela Souza',
    contato_numero: '11898011011',
    consultora: 'Júlia',
    status: 'vendido',
    score_ia: 97,
    classificacao_ia: 'vendido',
    chance_fechamento: 100,
    ultima_mensagem_at: hoursAgo(6),
    ultima_mensagem_texto: 'Pagamento confirmado! Obrigada 🎉',
    total_mensagens: 25,
    resumo_ia: 'Venda concluída. Lead muito satisfeita com o atendimento da Júlia. Candidata a indicar amigos.',
    objecoes_detectadas: [],
    erros_consultora: [],
    sugestoes_ia: ['Solicitar indicação de amigas', 'Convidar para grupo de alunos'],
    proxima_melhor_resposta: 'Daniela, seja bem-vinda à família EJA! Já te adicionei no grupo 🎓',
    recebeu_valor: true,
    recebeu_link: true,
    follow_up_enviado: true,
    tempo_resposta_medio: 15,
    tags: ['recebeu_valor', 'recebeu_link'],
  },
  {
    id: 'cv12',
    contato_nome: 'Paulo Roberto',
    contato_numero: '48877012012',
    consultora: 'Ketlen',
    status: 'frio',
    score_ia: 31,
    classificacao_ia: 'frio',
    chance_fechamento: 18,
    ultima_mensagem_at: daysAgo(2),
    ultima_mensagem_texto: 'Talvez no próximo mês',
    total_mensagens: 5,
    resumo_ia: 'Lead postergando decisão para o próximo mês. Risco de esfriar completamente.',
    objecoes_detectadas: ['Problema financeiro momentâneo', 'Adiando para o mês seguinte'],
    erros_consultora: ['Aceitou o adiamento sem explorar opções de entrada menor'],
    sugestoes_ia: ['Oferecer entrada menor ou boleto para iniciar', 'Lembrar que vaga pode não estar disponível no mês que vem'],
    proxima_melhor_resposta: 'Paulo, entendo! Mas sabia que tem opção de começar com uma entrada pequena? Me deixa te mostrar como funciona 😊',
    recebeu_valor: true,
    recebeu_link: false,
    follow_up_enviado: false,
    tempo_resposta_medio: 240,
    tags: ['recebeu_valor'],
  },
  {
    id: 'cv13',
    contato_nome: 'Renata Almeida',
    contato_numero: '11866013013',
    consultora: 'Tatiane',
    status: 'quente',
    score_ia: 76,
    classificacao_ia: 'quente',
    chance_fechamento: 68,
    ultima_mensagem_at: hoursAgo(1.8),
    ultima_mensagem_texto: 'Meu filho também quer fazer, tem desconto pra dois?',
    total_mensagens: 13,
    resumo_ia: 'Lead interessada e já indicou o filho. Oportunidade de venda dupla. Alta intenção de compra.',
    objecoes_detectadas: ['Quer desconto para dois'],
    erros_consultora: [],
    sugestoes_ia: ['Oferecer desconto família (15%)', 'Falar sobre inscrição simultânea', 'Fechar os dois hoje'],
    proxima_melhor_resposta: 'Que ótimo Renata! Para você e seu filho juntos, faço 15% de desconto nas duas matrículas. Vou confirmar as vagas pra vocês dois? 🎓',
    recebeu_valor: true,
    recebeu_link: false,
    follow_up_enviado: false,
    tempo_resposta_medio: 22,
    tags: ['recebeu_valor'],
  },
  {
    id: 'cv14',
    contato_nome: 'Sandro Pereira',
    contato_numero: '71855014014',
    consultora: 'Júlia',
    status: 'morno',
    score_ia: 58,
    classificacao_ia: 'morno',
    chance_fechamento: 42,
    ultima_mensagem_at: hoursAgo(9),
    ultima_mensagem_texto: 'O certificado é válido em todo Brasil?',
    total_mensagens: 10,
    resumo_ia: 'Lead fazendo perguntas técnicas sobre validade do certificado. Boa sinalização de interesse real.',
    objecoes_detectadas: ['Dúvida sobre reconhecimento do certificado'],
    erros_consultora: ['Não enviou documentação de reconhecimento MEC'],
    sugestoes_ia: ['Enviar comprovante de reconhecimento MEC', 'Compartilhar cases de alunos que usaram o certificado'],
    proxima_melhor_resposta: 'Sandro, nosso certificado é reconhecido pelo MEC em todo território nacional! Vou te enviar o documento de credenciamento agora 📄',
    recebeu_valor: true,
    recebeu_link: false,
    follow_up_enviado: false,
    tempo_resposta_medio: 60,
    tags: ['recebeu_valor'],
  },
  {
    id: 'cv15',
    contato_nome: 'Cristiane Martins',
    contato_numero: '31844015015',
    consultora: 'Ketlen',
    status: 'quente',
    score_ia: 85,
    classificacao_ia: 'quente',
    chance_fechamento: 80,
    ultima_mensagem_at: hoursAgo(1),
    ultima_mensagem_texto: 'Tá! Vou fazer pelo Pix mesmo, mais fácil',
    total_mensagens: 16,
    resumo_ia: 'Lead decidiu pela forma de pagamento (Pix). Praticamente fechada. Aguardando envio do link.',
    objecoes_detectadas: [],
    erros_consultora: ['Link ainda não foi enviado'],
    sugestoes_ia: ['Enviar chave Pix ou link de pagamento imediatamente', 'Confirmar em 15min se recebeu'],
    proxima_melhor_resposta: 'Perfeito Cristiane! Nossa chave Pix é: contato@ejaeducabrasil.com.br — Valor: R$ 297,00. Me confirma quando fizer? 💚',
    recebeu_valor: true,
    recebeu_link: false,
    follow_up_enviado: false,
    tempo_resposta_medio: 20,
    tags: ['recebeu_valor'],
  },
  {
    id: 'cv16',
    contato_nome: 'Gilberto Santos',
    contato_numero: '98833016016',
    consultora: 'Tatiane',
    status: 'frio',
    score_ia: 15,
    classificacao_ia: 'frio',
    chance_fechamento: 8,
    ultima_mensagem_at: daysAgo(4),
    ultima_mensagem_texto: 'Não to precisando não',
    total_mensagens: 3,
    resumo_ia: 'Lead sem interesse aparente. Conversa iniciou por engano ou lead errado.',
    objecoes_detectadas: ['Sem necessidade percebida'],
    erros_consultora: ['Não qualificou o lead antes de enviar proposta'],
    sugestoes_ia: ['Arquivar e não insistir', 'Revisar fonte do lead'],
    proxima_melhor_resposta: null,
    recebeu_valor: false,
    recebeu_link: false,
    follow_up_enviado: false,
    tempo_resposta_medio: 420,
    tags: [],
  },
  {
    id: 'cv17',
    contato_nome: 'Vanessa Lima',
    contato_numero: '11822017017',
    consultora: 'Júlia',
    status: 'quente',
    score_ia: 73,
    classificacao_ia: 'quente',
    chance_fechamento: 65,
    ultima_mensagem_at: hoursAgo(2.5),
    ultima_mensagem_texto: 'Consigo o diploma em quanto tempo?',
    total_mensagens: 12,
    resumo_ia: 'Lead perguntando sobre prazo do diploma — sinal de que está planejando usar o certificado. Interesse real e qualificado.',
    objecoes_detectadas: ['Quer prazo rápido para o diploma'],
    erros_consultora: [],
    sugestoes_ia: ['Informar prazo preciso do diploma', 'Mostrar exemplo de diploma para tangibilizar'],
    proxima_melhor_resposta: 'Vanessa, o diploma é emitido em até 30 dias após conclusão! E olha como fica 👉 [imagem]. Posso garantir sua vaga?',
    recebeu_valor: true,
    recebeu_link: false,
    follow_up_enviado: false,
    tempo_resposta_medio: 35,
    tags: ['recebeu_valor'],
  },
  {
    id: 'cv18',
    contato_nome: 'Márcio Barbosa',
    contato_numero: '21811018018',
    consultora: 'Ketlen',
    status: 'vendido',
    score_ia: 93,
    classificacao_ia: 'vendido',
    chance_fechamento: 100,
    ultima_mensagem_at: hoursAgo(10),
    ultima_mensagem_texto: 'Feito! Obrigado Ketlen, você é ótima!',
    total_mensagens: 20,
    resumo_ia: 'Venda fechada. Lead elogiou a consultora. Excelente oportunidade de pedir avaliação.',
    objecoes_detectadas: [],
    erros_consultora: [],
    sugestoes_ia: ['Pedir avaliação no Google', 'Solicitar indicação de amigos', 'Adicionar no grupo de alunos'],
    proxima_melhor_resposta: 'Que alegria Márcio! Seria incrível se você pudesse deixar uma avaliação pra gente ⭐⭐⭐⭐⭐',
    recebeu_valor: true,
    recebeu_link: true,
    follow_up_enviado: true,
    tempo_resposta_medio: 10,
    tags: ['recebeu_valor', 'recebeu_link'],
  },
  {
    id: 'cv19',
    contato_nome: 'Eliane Ferreira',
    contato_numero: '61800019019',
    consultora: 'Tatiane',
    status: 'morno',
    score_ia: 52,
    classificacao_ia: 'morno',
    chance_fechamento: 37,
    ultima_mensagem_at: hoursAgo(14),
    ultima_mensagem_texto: 'Fica em qual cidade? Tem online?',
    total_mensagens: 8,
    resumo_ia: 'Lead querendo informações geográficas — pode ser de cidade diferente. Modalidade online pode resolver.',
    objecoes_detectadas: ['Incerteza sobre localização/modalidade'],
    erros_consultora: ['Não perguntou de qual cidade o lead é antes de continuar'],
    sugestoes_ia: ['Perguntar cidade de origem', 'Apresentar modalidade 100% online', 'Destacar que o diploma tem validade nacional'],
    proxima_melhor_resposta: 'Eliane, temos modalidade 100% online! Você pode estudar de qualquer cidade do Brasil, no seu ritmo 📱',
    recebeu_valor: false,
    recebeu_link: false,
    follow_up_enviado: false,
    tempo_resposta_medio: 90,
    tags: [],
  },
  {
    id: 'cv20',
    contato_nome: 'Thiago Nascimento',
    contato_numero: '11799020020',
    consultora: 'Júlia',
    status: 'quente',
    score_ia: 81,
    classificacao_ia: 'quente',
    chance_fechamento: 74,
    ultima_mensagem_at: hoursAgo(0.8),
    ultima_mensagem_texto: 'Posso fazer em 3 meses? Tenho pressa',
    total_mensagens: 15,
    resumo_ia: 'Lead com urgência real — quer concluir rapidamente. Alta motivação. Consultora deve confirmar prazo acelerado.',
    objecoes_detectadas: ['Quer prazo acelerado'],
    erros_consultora: [],
    sugestoes_ia: ['Confirmar modalidade intensiva de 3 meses', 'Criar urgência para fechar hoje', 'Enviar link imediatamente'],
    proxima_melhor_resposta: 'Thiago, temos a modalidade intensiva onde você conclui em 3 meses! É exatamente o que você precisa. Vou reservar sua vaga? 🚀',
    recebeu_valor: true,
    recebeu_link: false,
    follow_up_enviado: false,
    tempo_resposta_medio: 25,
    tags: ['recebeu_valor'],
  },
]

export const MENSAGENS = {
  cv1: [
    { id: 'm1', de: 'lead', conteudo: 'Oi, vi o anúncio do curso EJA', enviado_at: hoursAgo(3) },
    { id: 'm2', de: 'consultora', conteudo: 'Olá Maria! Tudo bem? Que ótimo que você nos encontrou! 😊 O EJA Educa Brasil é o maior programa de certificação para adultos do país. Me conta, você quer concluir qual nível — fundamental ou médio?', enviado_at: hoursAgo(2.9) },
    { id: 'm3', de: 'lead', conteudo: 'Médio. Nunca terminei o ensino médio', enviado_at: hoursAgo(2.8) },
    { id: 'm4', de: 'consultora', conteudo: 'Entendo! Muitos adultos estão na mesma situação e o EJA é perfeito pra isso. Você sabia que com nosso certificado pode conseguir melhores oportunidades no mercado de trabalho? 📈', enviado_at: hoursAgo(2.7) },
    { id: 'm5', de: 'lead', conteudo: 'É mesmo? Quanto tempo leva?', enviado_at: hoursAgo(2.5) },
    { id: 'm6', de: 'consultora', conteudo: 'Pode concluir em 6 meses no ritmo normal ou 3 meses na modalidade intensiva! Tudo online, no seu tempo ⏰', enviado_at: hoursAgo(2.4) },
    { id: 'm7', de: 'lead', conteudo: 'Interessante! E quanto custa?', enviado_at: hoursAgo(2) },
    { id: 'm8', de: 'consultora', conteudo: 'O investimento é de R$ 297,00 e pode parcelar em até 12x! Hoje temos uma condição especial 🎯', enviado_at: hoursAgo(1.8) },
    { id: 'm9', de: 'lead', conteudo: 'Hmm deixa eu pensar...', enviado_at: hoursAgo(1.7) },
    { id: 'm10', de: 'consultora', conteudo: 'Claro! Mas fica sabendo que temos apenas 3 vagas disponíveis na turma de junho 👀', enviado_at: hoursAgo(1.6) },
    { id: 'm11', de: 'lead', conteudo: 'Nossa... 3 vagas só? Quanto é cada parcela?', enviado_at: hoursAgo(1.5) },
    { id: 'm12', de: 'consultora', conteudo: 'São 12x de R$ 29,70! Menos de R$ 1 por dia para mudar sua vida 💪 Vou te mandar o link de inscrição', enviado_at: hoursAgo(1.4) },
    { id: 'm13', de: 'lead', conteudo: 'Quanto custa o curso mesmo? Posso parcelar?', enviado_at: hoursAgo(1.2) },
    { id: 'm14', de: 'lead', tipo: 'audio', audio_url: null, duracao_segundos: 18, transcricao: 'Eu quero parcelar em mais vezes, tem como fazer em 24 vezes?', enviado_at: hoursAgo(1.0) },
    { id: 'm15', de: 'consultora', conteudo: 'Pode sim! Em 24x fica R$ 14,87 por mês 🎉', enviado_at: hoursAgo(0.9) },
  ],
}

export const ALERTAS = [
  {
    id: 'al1',
    conversa_id: 'cv4',
    tipo: 'sem_resposta_48h',
    descricao: 'Roberto Mendes está sem resposta há mais de 26h',
    severidade: 'critica',
    lido: false,
    created_at: hoursAgo(2),
    contato_nome: 'Roberto Mendes',
    consultora: 'Tatiane',
  },
  {
    id: 'al2',
    conversa_id: 'cv7',
    tipo: 'link_nao_enviado',
    descricao: 'Patrícia Oliveira pediu o link há 2h e ainda não recebeu',
    severidade: 'critica',
    lido: false,
    created_at: hoursAgo(2),
    contato_nome: 'Patrícia Oliveira',
    consultora: 'Tatiane',
  },
  {
    id: 'al3',
    conversa_id: 'cv15',
    tipo: 'link_nao_enviado',
    descricao: 'Cristiane Martins disse que vai pagar no Pix mas não recebeu os dados ainda',
    severidade: 'critica',
    lido: false,
    created_at: hoursAgo(1),
    contato_nome: 'Cristiane Martins',
    consultora: 'Ketlen',
  },
  {
    id: 'al4',
    conversa_id: 'cv2',
    tipo: 'lead_quente_sem_followup',
    descricao: 'José Carlos está morno há 5h sem follow-up agendado',
    severidade: 'atencao',
    lido: false,
    created_at: hoursAgo(5),
    contato_nome: 'José Carlos Silva',
    consultora: 'Júlia',
  },
  {
    id: 'al5',
    conversa_id: 'cv12',
    tipo: 'lead_frio',
    descricao: 'Paulo Roberto postergou decisão por 2 dias sem ação da consultora',
    severidade: 'atencao',
    lido: false,
    created_at: daysAgo(2),
    contato_nome: 'Paulo Roberto',
    consultora: 'Ketlen',
  },
  {
    id: 'al6',
    conversa_id: 'cv6',
    tipo: 'lead_quente_sem_followup',
    descricao: 'Fernando Lima aguarda resposta há 8h',
    severidade: 'aviso',
    lido: true,
    created_at: hoursAgo(8),
    contato_nome: 'Fernando Lima',
    consultora: 'Ketlen',
  },
  {
    id: 'al7',
    conversa_id: 'cv10',
    tipo: 'sem_resposta_12h',
    descricao: 'Marcos Vinicius sem contato há 12h',
    severidade: 'aviso',
    lido: false,
    created_at: hoursAgo(12),
    contato_nome: 'Marcos Vinicius',
    consultora: 'Tatiane',
  },
]

export const FOLLOWUPS = [
  {
    id: 'fu1',
    conversa_id: 'cv2',
    contato_nome: 'José Carlos Silva',
    consultora: 'Júlia',
    motivo: 'Lead morno com 5h sem resposta — retomar antes que esfrie',
    mensagem_sugerida: 'Oi José! Só passando pra saber se conseguiu pensar a respeito. Tenho uma vaga guardada pra você até amanhã 😊',
    status: 'pendente',
    created_at: hoursAgo(5),
  },
  {
    id: 'fu2',
    conversa_id: 'cv6',
    contato_nome: 'Fernando Lima',
    consultora: 'Ketlen',
    motivo: 'Lead disse que ia falar com a esposa — retomar com argumento para o casal',
    mensagem_sugerida: 'Oi Fernando! Boa tarde! Conseguiu falar com sua esposa? Teria uma surpresa pra vocês dois 😉',
    status: 'pendente',
    created_at: hoursAgo(8),
  },
  {
    id: 'fu3',
    conversa_id: 'cv10',
    contato_nome: 'Marcos Vinicius',
    consultora: 'Tatiane',
    motivo: 'Lead pediu mais informações mas ficou 12h sem resposta',
    mensagem_sugerida: 'Oi Marcos! Preparei um material especial com depoimentos de alunos pra você. Posso enviar?',
    status: 'pendente',
    created_at: hoursAgo(12),
  },
  {
    id: 'fu4',
    conversa_id: 'cv12',
    contato_nome: 'Paulo Roberto',
    consultora: 'Ketlen',
    motivo: 'Lead disse "próximo mês" — retomar com oferta especial',
    mensagem_sugerida: 'Oi Paulo! Surgiu uma novidade: temos uma entrada reduzida pra quem matricula essa semana. Quer saber mais?',
    status: 'pendente',
    created_at: daysAgo(2),
  },
  {
    id: 'fu5',
    conversa_id: 'cv14',
    contato_nome: 'Sandro Pereira',
    consultora: 'Júlia',
    motivo: 'Lead com dúvida sobre validade do certificado — enviar documentação',
    mensagem_sugerida: 'Oi Sandro! Aqui está o documento de credenciamento MEC do nosso programa 📄. Tirou a dúvida?',
    status: 'pendente',
    created_at: hoursAgo(9),
  },
  {
    id: 'fu6',
    conversa_id: 'cv19',
    contato_nome: 'Eliane Ferreira',
    consultora: 'Tatiane',
    motivo: 'Lead perguntou sobre localidade — explicar que é 100% online',
    mensagem_sugerida: 'Oi Eliane! Nosso curso é 100% online, você estuda de qualquer lugar do Brasil 📱. De onde você é?',
    status: 'enviado',
    enviado_at: hoursAgo(10),
    created_at: hoursAgo(14),
  },
]

export const MARCACOES = [
  { id: 'mc1', conversa_id: 'cv1', tipo: 'recebeu_valor', nota: 'Enviou tabela de preços e parcelamento', criado_por: 'Tatiane', created_at: hoursAgo(1.8), contato_nome: 'Maria Aparecida' },
  { id: 'mc2', conversa_id: 'cv1', tipo: 'recebeu_link', nota: 'Link do checkout enviado', criado_por: 'Tatiane', created_at: hoursAgo(1.4), contato_nome: 'Maria Aparecida' },
  { id: 'mc3', conversa_id: 'cv3', tipo: 'vendido', nota: 'Pagamento confirmado via Pix', criado_por: 'Ketlen', created_at: hoursAgo(3), contato_nome: 'Ana Paula Ferreira' },
  { id: 'mc4', conversa_id: 'cv5', tipo: 'recebeu_valor', nota: 'Tabela de preços turma SP enviada', criado_por: 'Júlia', created_at: hoursAgo(2), contato_nome: 'Luciana Costa' },
  { id: 'mc5', conversa_id: 'cv7', tipo: 'recebeu_valor', nota: 'Proposta de preço e turmas enviada', criado_por: 'Tatiane', created_at: hoursAgo(3), contato_nome: 'Patrícia Oliveira' },
  { id: 'mc6', conversa_id: 'cv11', tipo: 'vendido', nota: 'Pagamento confirmado no cartão', criado_por: 'Júlia', created_at: hoursAgo(6), contato_nome: 'Daniela Souza' },
  { id: 'mc7', conversa_id: 'cv18', tipo: 'vendido', nota: 'Pagamento Pix confirmado', criado_por: 'Ketlen', created_at: hoursAgo(10), contato_nome: 'Márcio Barbosa' },
]

export const METRICAS_DASHBOARD = {
  conversas_abertas: 14,
  leads_quentes: 7,
  alertas_ativos: 6,
  followups_pendentes: 5,
  score_medio_time: 64,
  sem_resposta_24h: 3,
  vendas_hoje: 2,
  taxa_fechamento: 18,
}

export const METRICAS_POR_CONSULTORA = [
  { consultora: 'Tatiane', abertas: 6, quentes: 3, score_medio: 67, vendas: 0, ultima_atividade: hoursAgo(1.2) },
  { consultora: 'Júlia', abertas: 5, quentes: 2, score_medio: 62, vendas: 1, ultima_atividade: hoursAgo(0.5) },
  { consultora: 'Ketlen', abertas: 5, quentes: 2, score_medio: 71, vendas: 2, ultima_atividade: hoursAgo(0.3) },
]

export const HISTORICO_SEMANA = [
  { dia: 'Seg', quente: 4, morno: 6, frio: 3, vendido: 1 },
  { dia: 'Ter', quente: 5, morno: 4, frio: 2, vendido: 2 },
  { dia: 'Qua', quente: 3, morno: 7, frio: 4, vendido: 1 },
  { dia: 'Qui', quente: 6, morno: 5, frio: 2, vendido: 3 },
  { dia: 'Sex', quente: 7, morno: 3, frio: 3, vendido: 2 },
  { dia: 'Sab', quente: 4, morno: 4, frio: 5, vendido: 1 },
  { dia: 'Dom', quente: 2, morno: 3, frio: 6, vendido: 0 },
]
